.github/workflows/integrate.yaml, CHANGELOG.md, cabal.project, nix/sources.json, plutus-extra.cabal
Raises the Plutus version to the most recent one. Additionally fixes a range of style guide issues, both in the Cabal file and the changelog.
=> Bump plutus

tasty-plutus/src/Test/Tasty/Plutus/Options.hs, tasty-plutus/src/Test/Tasty/Plutus/Options/QQ.hs, tasty-plutus/tasty-plutus.cabal
=> Quasiquoters for property-based options

tasty-plutus/src/Test/Tasty/Plutus/Context.hs, tasty-plutus/src/Test/Tasty/Plutus/TestData.hs
Closes #31. @nrutledge - does this clarify things sufficiently? I'll definitely want to redesign this API to be more convenient, but for now, I can at least document existing behaviour.
=> [WIP] Document how to deal with self-spends

README.md, cabal.project, plutus-numeric/CHANGELOG.md, plutus-numeric/Makefile, plutus-numeric/README.md, plutus-numeric/plutus-numeric.cabal, plutus-numeric/src/PlutusTx/NatRatio.hs, plutus-numeric/src/PlutusTx/NatRatio/Internal.hs, plutus-numeric/src/PlutusTx/NatRatio/QQ.hs, plutus-numeric/src/PlutusTx/Natural.hs, plutus-numeric/src/PlutusTx/Natural/Internal.hs, plutus-numeric/src/PlutusTx/Natural/QQ.hs, plutus-numeric/src/PlutusTx/Numeric/Extra.hs, plutus-numeric/test/Compilation.hs, plutus-numeric/test/Helpers.hs, plutus-numeric/test/Main.hs, plutus-numeric/test/Suites/NatRatio.hs, plutus-numeric/test/Suites/Natural.hs, plutus-numeric/test/Suites/Numeric.hs
This creates a new sub-library `plutus-numeric`, containing numerical hierarchy extensions, as well as tests for these.
=> Import Plutus numerical hierarchy

tasty-plutus/CHANGELOG.md, tasty-plutus/src/Test/Tasty/Plutus/Internal.hs, tasty-plutus/src/Test/Tasty/Plutus/Options.hs, tasty-plutus/src/Test/Tasty/Plutus/Script/Property.hs, tasty-plutus/src/Test/Tasty/Plutus/Script/Unit.hs, tasty-plutus/tasty-plutus.cabal
Closes #53 and #63. This creates a minor version bump for `tasty-plutus`.
=> Wire up ScriptInputPosition, make ContextBuilder a Monoid

tasty-plutus/CHANGELOG.md, tasty-plutus/README.md, tasty-plutus/src/Test/Tasty/Plutus/Script/Size.hs, tasty-plutus/tasty-plutus.cabal
This provides a new `tasty-plutus` testing API for checking the on-chain size of scripts.
=> Script size testing

quickcheck-plutus-instances/CHANGELOG.md, quickcheck-plutus-instances/quickcheck-plutus-instances.cabal, quickcheck-plutus-instances/src/Test/QuickCheck/Plutus/Instances.hs, quickcheck-plutus-instances/src/Test/QuickCheck/Plutus/Modifiers.hs
This closes #82, as well as providing more instances and helpers.
=> Fix Arbitrary instance for Value

tasty-plutus/CHANGELOG.md, tasty-plutus/src/Test/Tasty/Plutus/Script/Property.hs, tasty-plutus/src/Test/Tasty/Plutus/Script/Unit.hs, tasty-plutus/src/Test/Tasty/Plutus/TestData.hs
=> Unify `Example` and `Outcome`

quickcheck-plutus-instances/CHANGELOG.md, quickcheck-plutus-instances/quickcheck-plutus-instances.cabal, quickcheck-plutus-instances/src/Test/QuickCheck/Plutus/Instances.hs
=> QuickCheck instances for AssetClass

.github/workflows/integrate.yaml
=> Fix GitHub actions

tasty-plutus/CHANGELOG.md, tasty-plutus/src/Test/Tasty/Plutus/Context.hs, tasty-plutus/src/Test/Tasty/Plutus/Internal/Context.hs, tasty-plutus/src/Test/Tasty/Plutus/Script/Property.hs, tasty-plutus/src/Test/Tasty/Plutus/TestData.hs
Fixes problems introduced by #77, which was broken.
=> Fix property tests for minting policies

cabal.project, plutus-deriving/CHANGELOG.md, plutus-deriving/Makefile, plutus-deriving/README.md, plutus-deriving/plutus-deriving.cabal, plutus-deriving/src/PlutusTx/Deriving.hs, plutus-deriving/test/Test.hs, plutus-deriving/test/laws/Main.hs, plutus-deriving/test/size/Main.hs
This introduces a new helper library `plutus-deriving`, which provides TH-based auto-derivation. Currently, this only supports Plutus' `Eq`. We also have tests to ensure the generated code is law-abiding, and also for size.
=> TH-based Plutus Eq deriving

plutus-pretty/README.md, plutus-pretty/plutus-pretty.cabal, plutus-pretty/src/PlutusTx/Skeleton.hs, plutus-pretty/src/PlutusTx/Skeleton/Builder.hs, plutus-pretty/src/PlutusTx/Skeleton/Internal.hs, plutus-pretty/src/PlutusTx/Skeleton/QQ.hs, plutus-pretty/test/properties/Main.hs, plutus-pretty/test/script-size/Main.hs
We now output JSON using `showSkeletal`.
=> Fix issues with showSkeletal, use JSON representation

tasty-plutus/CHANGELOG.md, tasty-plutus/src/Test/Tasty/Plutus/Script/Property.hs, tasty-plutus/test/Properties/Main.hs
Add `scriptPropertyPass` and `scriptPropertyFail`
=> Sergesku/property testing#89

plutus-deriving/plutus-deriving.cabal, plutus-extra/CHANGELOG.md, plutus-extra/plutus-extra.cabal, plutus-extra/src/PlutusTx/NonEmpty.hs, plutus-extra/test/Suites/PlutusTx/NonEmpty.hs, plutus-pretty/plutus-pretty.cabal, quickcheck-plutus-instances/CHANGELOG.md, quickcheck-plutus-instances/quickcheck-plutus-instances.cabal, quickcheck-plutus-instances/src/Test/QuickCheck/Plutus/Instances.hs
- Instances of `Eq`, `Ord`, `Arbitrary`, `CoArbitrary`
and `Function` for `NonEmpty`
- Instances of `Arbitrary`, `CoArbitrary` and `Function` for
`PlutusTx.Ratio.Rational`
=> Instances for `PlutusTx.Rational` and `NonEmpty`

tasty-plutus/CHANGELOG.md, tasty-plutus/src/Test/Tasty/Plutus/Internal/Context.hs, tasty-plutus/src/Test/Tasty/Plutus/Internal/Env.hs, tasty-plutus/src/Test/Tasty/Plutus/Internal/WithScript.hs, tasty-plutus/src/Test/Tasty/Plutus/Script/Property.hs, tasty-plutus/src/Test/Tasty/Plutus/Script/Unit.hs, tasty-plutus/src/Test/Tasty/Plutus/TestData.hs, tasty-plutus/src/Test/Tasty/Plutus/WithScript.hs, tasty-plutus/tasty-plutus.cabal, tasty-plutus/test/Properties/Main.hs
Addresses [#24 ](https://github.com/Liqwid-Labs/plutus-extra/issues/24)
WIP: toTestValidator for TypedValidators needs to be implemented.
=> Extend Purpose with additional type parameters.

plutus-numeric/plutus-numeric.cabal, plutus-numeric/src/PlutusTx/Natural/Internal.hs, plutus-numeric/src/PlutusTx/Numeric/Extra.hs, plutus-numeric/test/natural-compare-size/Main.hs, plutus-numeric/test/size/Integer.hs, plutus-numeric/test/size/Main.hs, plutus-numeric/test/size/NatRatio.hs, plutus-numeric/test/size/Natural.hs
This applies similar fixes as the ones for `NatRatio` and `Rational`, as well as 'pinning' the sizes of `Natural` functions to ensure we don't regress on size.
=> Improve Natural

plutus-numeric/src/PlutusTx/Natural/Internal.hs, tasty-plutus/src/Test/Tasty/Plutus/Context.hs, tasty-plutus/src/Test/Tasty/Plutus/Options/QQ.hs
- changed description of functions for constructing `ContextBuilder`
- fixed _QQ_ error message
- fixed implementation of Arbitrary instance (__shrink__) for `Natural`
=> Small fixes for `plutus-numeric` and `tasty-plutus`

flake.nix, plutus-deriving/Makefile, plutus-extra/Makefile, plutus-extra/plutus-extra.cabal, plutus-golden/Makefile, plutus-laws/Makefile, plutus-numeric/Makefile, plutus-pretty/Makefile, plutus-size-check/Makefile, quickcheck-plutus-instances/Makefile, tasty-plutus/Makefile
- Add `entr`, `nixfmt`, `cabalfmt` to nix shell
- Fix `Makefile`: watch, nixfmt, cabalfmt
=> Add `shell` dependencies, Fix `Makefile`

tasty-plutus/CHANGELOG.md, tasty-plutus/src/Test/Tasty/Plutus/WithScript.hs
=> Allow custom script context type in `toTestValidator`/`toTestMintingPolicy`

tasty-plutus/CHANGELOG.md, tasty-plutus/src/Test/Tasty/Plutus/Context.hs, tasty-plutus/src/Test/Tasty/Plutus/Internal/Context.hs, tasty-plutus/tasty-plutus.cabal
Solves: https://github.com/Liqwid-Labs/plutus-extra/issues/158
=> Add optional datum to payToPubKey functions

plutus-extra/CHANGELOG.md, plutus-extra/plutus-extra.cabal, plutus-extra/src/Plutus/Contract/Test/Extra.hs, tasty-plutus/tasty-plutus.cabal
Fixes #155. The current function signature might not be optimal.
=> Add `utxoAtAddress` and export `utxoAtComputedAddress`

quickcheck-plutus-instances/src/Test/QuickCheck/Plutus/Instances.hs
Shrink has been omitted because shrinking doesn't make sense on fixed-length values.
I am not sure all the hash algorithms are correct as I'm getting mixed messages from various sources. I would appreciate a review from someone who knows what they're talking about.
=> Attempt to write correct arbitrary instances for fixed-length values

plutus-deriving/plutus-deriving.cabal, plutus-numeric/plutus-numeric.cabal, plutus-pretty/plutus-pretty.cabal, quickcheck-plutus-instances/CHANGELOG.md, quickcheck-plutus-instances/quickcheck-plutus-instances.cabal, quickcheck-plutus-instances/src/Test/QuickCheck/Plutus/Instances.hs, tasty-plutus/tasty-plutus.cabal
=> Remove the generation of `StakingPtr` from `Arbitrary StakingCredential`

plutus-laws/src/Test/Tasty/Plutus/Laws.hs
Fixes #196; also rewords the descriptions of a few laws that don't properly correspond to their implementations.
=> Fix incorrect Eq transitivity law

hie.yaml, tasty-plutus/src/Test/Tasty/Plutus/Script/Property.hs
=> Fix out-of-sync property check logs

.github/lint.sh, .github/workflows/integrate.yaml, plutus-deriving/src/PlutusTx/Deriving.hs, plutus-numeric/src/PlutusTx/NatRatio/QQ.hs, plutus-numeric/src/PlutusTx/Natural/QQ.hs, plutus-numeric/src/PlutusTx/Positive/QQ.hs, plutus-numeric/src/PlutusTx/Rational/QQ.hs, plutus-numeric/test/size/Integer.hs, plutus-numeric/test/size/NatRatio.hs, plutus-numeric/test/size/Natural.hs, plutus-pretty/src/PlutusTx/Skeleton/QQ.hs, plutus-size-check/src/Test/Tasty/Plutus/QQ.hs, quickcheck-plutus-instances/src/Test/QuickCheck/Plutus/Instances.hs, tasty-plutus/src/Test/Tasty/Plutus/Options/QQ.hs, tasty-plutus/test/Properties/Main.hs
=> Fix HLint in CI
